#!/bin/bash
# BEGIN-INCLUDE LICENSE-header
# END-INCLUDE
if [[ -z "$SHXMLSHARE" ]];then
    echo "!! \$SHXMLSHARE not set. Run as 'shxml backend $(basename "$0")' !!"
    exit 142
fi
source "$SHXMLSHARE/lib/common.bash"
source "$SHXMLSHARE/lib/java.bash"

SYNOPSIS="Run Xalan-J JAR"

usage () {
    echo "Usage: $SHXMLBINARY backend xalan-j -- <args>

    Run '$SHXMLBINARY backend xalan-j -- -h' for more help."
}

while [[ "$1" && "$1" != "--" ]];do
    case "$1" in
        ## --synopsis
        --synopsis) echo "$SYNOPSIS"; exit ;;
        ## --check-installed
        --check-installed) _shxml_mark_ok ; exit ;;
        *) shlog -l error "Unknown option '$1'"; usage; exit 7 ;;
    esac
    shift
done
shift || { usage; exit; }
CLASSPATH="$SHXMLSHARE/deps/jar/xalan-serializer.jar:$SHXMLSHARE/deps/jar/xalan.jar"

_shxml_exec  "$JAVACMD" "${JVM_OPTS[@]}" -cp "$CLASSPATH" "org.apache.xalan.xslt.Process" "$@"
