#!/bin/bash
# BEGIN-INCLUDE LICENSE-header
# END-INCLUDE
if [[ -z "$SHXMLSHARE" ]];then
    echo "!! \$SHXMLSHARE not set. Run as 'shxml backend $(basename "$0")' !!"
    exit 142
fi
source "$SHXMLSHARE/lib/common.bash"

SYNOPSIS="Run xmlstarlet"

SHXML_XMLSTARLET="${SHXML_XMLSTARLET:-xmlstarlet}"

usage () {
    echo "Usage: $SHXMLBINARY backend xmlstarlet [opts] -- <args>

    $SYNOPSIS

    Run '$SHXMLBINARY backend xmlstarlet -- --help' for more help."
}

while [[ "$1" && "$1" != "--" ]];do
    case "$1" in
        ## ### --synopsis
        --synopsis) echo "$SYNOPSIS"; exit ;;
        --check-installed)
            if [[ -x "$SHXML_XMLSTARLET" ]];then
                _shxml_mark_ok; exit
            elif compgen -c "$SHXML_XMLSTARLET" >/dev/null;then
                _shxml_mark_ok; exit
            fi
            _shxml_mark_notok; exit 1
            ;;
        *) shlog -l error "Unknown option '$1'"; usage; exit 7 ;;
    esac
    shift
done
shift || { usage; exit; }

shlog -l trace exec "$SHXML_XMLSTARLET" "$@"
exec "$SHXML_XMLSTARLET" "$@"
