#!/bin/bash
# BEGIN-INCLUDE LICENSE-header
# END-INCLUDE
if [[ -z "$SHXMLSHARE" ]];then
    echo "!! \$SHXMLSHARE not set. Run as '$(echo "$0"|sed -e 's,.*/,,' -e 's,-, ,')' !!"
    exit 142
fi
source "$SHXMLSHARE/lib/common.bash"

SHXML_BACKENDS_XSLT=("saxon" "xsltproc" "xalan-cpp" "xalan-j" "xmlstarlet")
SYNOPSIS="Transform XML with XSLT"
declare -A \
    SHXML_XSLT_PARAMS \
    SHXML_XSLT_OUTPUT_PARAMS

usage() {
    echo "shxml xslt [opts] <xslt> <input-file...>

    $SYNOPSIS

    Options:

        --backend <BACKEND>         Use specific backend <BACKEND>
        --list-backends             List available backends
        -p --param <K> <V>          Let stylesheet parameter <K>=<V>
        -O --output-param <K> <V>   Let xsl:output attribute <K>=<V>
"
}

## ## OPTIONS
##
while [[ "$1" = -?* ]];do
    case "$1" in
        #help:--synopsis:Show the synopsis of this command
        --synopsis) echo "$SYNOPSIS"; exit ;;
        --backend) BACKEND="$2"; shift ;;
        -p|--param) SHXML_XSLT_PARAMS[$2]="$3"; shift; shift ;;
        # -P|--string-param) SHXML_XSLT_PARAMS[$2]="\"${3//"/\\"}\""; shift; shift ;;
        -O|--output-param) SHXML_XSLT_OUTPUT_PARAMS[$2]="$3"; shift; shift ;;
        --list-backends)
            _shxml_backend_check_installed "${SHXML_BACKENDS_XSLT[@]}"
            exit ;;
    esac
    shift
done
[[ -z "$1" ]] && { usage; exit; }

## ## ARGUMENTS

##
## * <xslt> - the xslt script to use
##
XSLT="$1"
if [[ ! -r "$XSLT" ]];then
    shlog -l error -x 2 "Cannot read XSLT script '$XSLT'"
fi
shift

## * [input-file...] - input files or a single dash for stdin
##
declare -a INPUT_FILES
_args_input_files_or_stdin "$@"
INPUT_FILES=("${_ARGS_INPUT_FILES[@]}")

if [[ -z "$BACKEND" ]];then
    #shellcheck disable=SC2153
    _shxml_backend_determine "$SHXML_BACKEND_XSLT" "${SHXML_BACKENDS_XSLT[@]}"
fi
shlog -l trace "XSLT BACKEND: '$BACKEND'"
shlog -l trace "XSLT: '$XSLT'"
shlog -l trace "INPUT_FILES: '${INPUT_FILES[*]}'"
case "$BACKEND" in
    # param=value           Set stylesheet string parameter
    # +param=filename       Set stylesheet document parameter
    # ?param=expression     Set stylesheet parameter using XPath
    # !param=value          Set serialization parameter
    saxon)
        typeset -a SAXON_FLAGS SAXON_ARGS
        for k in "${!SHXML_XSLT_PARAMS[@]}";do
            SAXON_ARGS+=("${k}=${SHXML_XSLT_PARAMS[$k]}")
        done
        for k in "${!SHXML_XSLT_OUTPUT_PARAMS[@]}";do
            SAXON_ARGS+=("!${k}=${SHXML_XSLT_OUTPUT_PARAMS[$k]}")
        done
        for input_file in "${INPUT_FILES[@]}";do
            $SHXMLBINARY backend "$BACKEND" -- \
                "Transform" \
                "${SAXON_FLAGS[@]}" \
                -xsl:"$XSLT" \
                -s:"$input_file" \
                "${SAXON_ARGS[@]}"
        done
        ;;
    xalan-j)
        for input_file in "${INPUT_FILES[@]}";do
            _shxml_backend "$BACKEND" -- \
                -xsl "$XSLT" \
                -in "$input_file"
        done
        ;;
    xalan-cpp)
        for input_file in "${INPUT_FILES[@]}";do
            $SHXMLBINARY backend "$BACKEND" -- \
                -xsl "$XSLT" \
                -in "$input_file"
        done
        ;;
    xsltproc)
        for input_file in "${INPUT_FILES[@]}";do
            declare -a XSLTPROC_ARGS
            if [[ "${#SHXML_XSLT_OUTPUT_PARAMS}" -gt 0 ]];then
                shlog -l warn "xsltproc does not support setting output parameters on the CLI! Ignoring ${SHXML_XSLT_OUTPUT_PARAMS[*]}"
            fi
            for k in "${!SHXML_XSLT_PARAMS[@]}";do
                XSLTPROC_ARGS+=("--param" "$k" "${SHXML_XSLT_PARAMS[$k]}")
            done
            shxml-backend "$BACKEND" -- "${XSLTPROC_ARGS[@]}" "$XSLT" "$input_file"
        done
        ;;
    xmlstarlet)
        for input_file in "${INPUT_FILES[@]}";do
            shxml-backend "$BACKEND" -- \
                "transform" \
                "$XSLT" \
                "$input_file"
        done
        ;;
esac
