#!/bin/bash

# BEGIN-INCLUDE LICENSE-header
# END-INCLUDE

if [[ -z "$SHXMLSHARE" ]];then
    echo "!! \$SHXMLSHARE not set. Run as '$(echo "$0"|sed -e 's,.*/,,' -e 's,-, ,')' !!"
    exit 142
fi
source "$SHXMLSHARE/lib/common.bash"

SYNOPSIS="Run a backend directly"

usage() {
    echo "Usage: $SHXMLBINARY backend <backend> [backend-args...]

    Backends:
"
    _shxml_backend_check_installed "${SHXMLBACKENDS[@]}"

    echo "
    Run '$SHXMLBINARY backend <command> --help to get backend-specific help"
}

## ## OPTIONS
##
while [[ "$1" = -?* ]];do
    case "$1" in
        ## ### --synopsis
        ##
        ## Show the synopsis of this command
        ##
        -h|--help) usage; exit ;;
        --synopsis) echo "$SYNOPSIS"; exit ;;
        *) shlog -l error -x 7 "Unknown option '$1'"; exit ;;
    esac
    shift
done

## ## ARGUMENTS
##
## * <xsd> - the XSD schema
##
BACKEND="$1"
if [[ -z "$BACKEND" ]];then
    usage
    exit
elif [[ ! -e "$SHXMLSHARE/lib/backend/$BACKEND" ]] >/dev/null;then
    shlog -l error -x 9 "Unknown backend '$BACKEND'"
fi
shift

shlog -l trace "BACKEND: '$BACKEND'"
shlog -l trace "\$@: " "$@"
_shxml_backend "$BACKEND" "$@"
